name: CI/CD Pipeline - HealthTrack App (Solo Revision y Dependencias)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-check-code: # Nombre del trabajo ajustado
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Check Dependencies (No Tests)
        # Ejecuta el servicio 'unit-tests' pero sobrescribe su comando
        # para solo limpiar e instalar dependencias, sin ejecutar pruebas.
        # Esto verifica que el código compila y que las dependencias se resuelven.
        run: docker compose run --rm unit-tests mvn clean install -DskipTests

      - name: Build Webapp Image
        # Construye solo la imagen de la webapp.
        run: docker compose build webapp

      - name: Deploy and Test Webapp Health
        # Levanta la webapp y espera a que su healthcheck pase.
        # Esto simula un despliegue y verifica que el servidor web está operativo.
        run: docker compose up --abort-on-container-exit --wait webapp

      - name: Stop and Remove Containers
        # Asegura que los contenedores se detengan y eliminen, incluso si algún paso anterior falla.
        if: always()
        run: docker compose down
