name: CI/CD Pipeline - HealthTrack App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Run Unit Tests
        # Ejecuta el servicio 'unit-tests' definido en docker-compose.yml
        # Maven ejecutará los tests unitarios y generará los reportes
        run: docker compose run --rm unit-tests

      - name: Build Docker Images (functional-tests, performance-tests & webapp)
        # Construye todas las imágenes necesarias para las pruebas funcionales y de rendimiento
        run: docker compose build functional-tests performance-tests webapp

      - name: Run Functional Tests
        # Levanta la webapp y ejecuta los tests funcionales
        # --abort-on-container-exit detiene los servicios una vez que functional-tests termina
        run: docker compose up --abort-on-container-exit functional-tests webapp

      - name: Run Performance Tests
        # Levanta la webapp y ejecuta los tests de rendimiento con JMeter
        # --abort-on-container-exit detiene los servicios una vez que performance-tests termina
        run: docker compose up --abort-on-container-exit performance-tests webapp

      - name: Stop and Remove Containers
        # Asegura que los contenedores se detengan y eliminen, incluso si algún paso anterior falla
        if: always()
        run: docker compose down
